BEGIN;

CREATE TABLE IF NOT EXISTS users_schema."user"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "firstName" character varying NOT NULL,
    "secondName" character varying,
    "middleName" character varying,
    "e-mail" character varying,
    phone character varying,
    about character varying,
    photo character varying,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_schema.subscriprion
(
    user_id bigint NOT NULL,
    subscriber_id bigint NOT NULL,
    CONSTRAINT subscriprion_subscriber_id_fkey FOREIGN KEY (subscriber_id)
        REFERENCES users_schema."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT subscriprion_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users_schema."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION

);

END;